/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg11_Hasinbp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SMKN4
 */
public class tambah_data extends javax.swing.JFrame {

    /**
     * Creates new form tambah_data
     */
    Connection connection = DatabaseConnection.getConnection();
    ResultSet rs;
    Statement stmt;
    int baris;
    String action;
    public tambah_data(String id_inventaris, String act) {
        initComponents();
        action = act;
        if (action.equals("edit")) {
            txt_idInventaris.setEnabled(false);
            ShowData(id_inventaris);
        }
        
        
        addpetugas();
        addKeterangan();
        addJenis();
        addRuang();
    }

    private tambah_data() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    tambah_data(Data_inventaris aThis, boolean b, String edit, String id_inventaris) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_idInventaris = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_kondisi = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        txt_jumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_keterangan = new javax.swing.JComboBox<>();
        cb_jenis = new javax.swing.JComboBox<>();
        cb_ruang = new javax.swing.JComboBox<>();
        cb_petugas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel2.setText("Id Inventaris :");

        jLabel3.setText("Nama :");

        jLabel4.setText("Kondisi :");

        jLabel5.setText("Keterangan :");

        jLabel6.setText("Jumlah :");

        jLabel7.setText("Jenis :");

        jLabel8.setText("Tanggal :");

        jLabel9.setText("Ruang :");

        jLabel10.setText("Petugas :");

        cb_keterangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select :" }));

        cb_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select :" }));

        cb_ruang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select :" }));

        cb_petugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select :" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btn_submit)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(txt_kondisi, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(txt_idInventaris)
                    .addComponent(cb_keterangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_ruang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_petugas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idInventaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btn_submit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        insertdata();
    }//GEN-LAST:event_btn_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JComboBox<String> cb_keterangan;
    private javax.swing.JComboBox<String> cb_petugas;
    private javax.swing.JComboBox<String> cb_ruang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_idInventaris;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kondisi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tgl;
    // End of variables declaration//GEN-END:variables


   public void insertdata(){
       String id_inventaris = txt_idInventaris.getText();
       String nama = txt_nama.getText();
       String Kondisi = txt_kondisi.getText();
       String keterangan = cb_keterangan.getSelectedItem().toString();
       String jumlah = txt_jumlah.getText();
       String jenis = cb_jenis.getSelectedItem().toString();
       String tanggal = txt_tgl.getText();
       String ruang = cb_ruang.getSelectedItem().toString();
       String petugas = cb_petugas.getSelectedItem().toString();
       
       try {
           String query = "INSERT INTO `inventaris` (`id_inventaris`, `nama`,`kondisi`,`keterangan`,`jumlah`,`id_jenis`,`tanggal_register`,`id_ruang`,`id_petugas`)"
                   + "VALUES ('"+id_inventaris+"','"+nama+"',"
                   + "'"+Kondisi+"','"+keterangan+"','"+jumlah+"','"+jenis+"','"+tanggal+"',"
                   + "'"+ruang+"','"+petugas+"');";
           stmt = connection.createStatement();
           int i = stmt.executeUpdate(query);
           System.out.println(query);
           
           if (i == 1) {
               JOptionPane.showMessageDialog(this, "Data Berhasil Dimasukkan");
               Data_inventaris invent = new Data_inventaris();
               invent.viewInventaris();
           }
           else{
               JOptionPane.showMessageDialog(this, "Data gagal dimasukkan");
           }
       } catch (Exception e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "koneksi gagal");
       }
       
   }
   
   public void addKeterangan(){

       try {
            String query = "SELECT * FROM jenis";
            stmt = connection.createStatement();
            rs = stmt.executeQuery(query);   
            
            while (rs.next()) {
                String item = rs.getString("keterangan");
                cb_keterangan.addItem(item);
           }
       } catch (SQLException e) {
           System.out.println("Koneksi Gagal" + e.getMessage());
       }
   }
   
    public void addJenis(){

       try {
            String query = "SELECT * FROM jenis";
            stmt = connection.createStatement();
            rs = stmt.executeQuery(query);   
            
            while (rs.next()) {
                String item = rs.getString("id_jenis");
                cb_jenis.addItem(item);
           }
       } catch (SQLException e) {
           System.out.println("Koneksi Gagal" + e.getMessage());
       }
   }
   public void addRuang(){

       try {
            String query = "SELECT * FROM ruang";
            stmt = connection.createStatement();
            rs = stmt.executeQuery(query);   
            
            while (rs.next()) {
                String item = rs.getString("id_ruang");
                cb_ruang.addItem(item);
           }
       } catch (SQLException e) {
           System.out.println("Koneksi Gagal" + e.getMessage());
       }
   }
   
   public void addpetugas(){

       try {
            String query = "SELECT * FROM petugas";
            stmt = connection.createStatement();
            rs = stmt.executeQuery(query);   
            
            while (rs.next()) {
                String item = rs.getString("id_petugas");
                cb_petugas.addItem(item);
           }
       } catch (SQLException e) {
           System.out.println("Koneksi Gagal" + e.getMessage());
       }
   }   
   
   void ShowData(String id_inventaris){
        try{
            Statement stmt = connection.createStatement();
            String query = "SELECT * FROM inventaris WHERE id_inventaris = '"+id_inventaris+"'";
            ResultSet rs = stmt.executeQuery(query);
            rs.next();

            
            txt_nama.setText(rs.getString("nama"));
            txt_kondisi.setText(rs.getString("kondisi"));
            cb_keterangan.setSelectedItem(rs.getString("keterangan"));
            txt_jumlah.setText(rs.getString("jumlah"));
            cb_jenis.setSelectedItem(rs.getString("jenis"));
            txt_tgl.setText(rs.getString("tanggal"));
            cb_ruang.setSelectedItem(rs.getString("ruang"));
            cb_petugas.setSelectedItem(rs.getString("petugas"));
             

        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di query");
        }

    }
   
   public void Editdata(String id_inventaris){
       String nama = txt_nama.getText();
       String Kondisi = txt_kondisi.getText();
       addKeterangan();
       String keterangan = cb_keterangan.getSelectedItem().toString();
       String jumlah = txt_jumlah.getText();
       addJenis();
       String jenis = cb_jenis.getSelectedItem().toString();
       String tanggal = txt_tgl.getText();
       addRuang();
       String ruang = cb_ruang.getSelectedItem().toString();
       addpetugas();
       String petugas = cb_petugas.getSelectedItem().toString();

        

        
        try{
            Statement stmt = connection.createStatement();
            String query = "UPDATE inventaris SET nama = '"+nama+"',"+"kondisi='"+Kondisi+"',"+"keterangan='"+keterangan+
                    "',"+"jumlah='"+jumlah+"',"+"tanggal_register='"+tanggal+"',"+"ruang='"+ruang+",petugas = '"+petugas+"'"
                    + "  'WHERE id_inventaris = '"+id_inventaris+"'";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1){
                JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            }
            else {
                JOptionPane.showMessageDialog(null, "Data gagal di ubah");
            }
            
        } catch(SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada query");
        }
    }
      
      
      
      

}
